# .github/workflows/docker-build.yml

name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 소스 체크아웃
      - name: Check out the code
        uses: actions/checkout@v2

      # ACR 로그인
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      # 프론트엔드 Docker 이미지 빌드 및 푸시
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: <your-acr-login-server>/<frontend-image-name>:latest
          platforms: linux/amd64,linux/arm64

      # 백엔드 Docker 이미지 빌드 및 푸시
      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: <your-acr-login-server>/<backend-image-name>:latest
          platforms: linux/amd64,linux/arm64
